### ISSUE TITLE
Cannot create symlink from /usr/share/wordlists to ~/wordlists if folder exists

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/kali-ansible-setup#5]
Create symbolic link to wordlists folder] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "gid": 1000, "group": "zweilos", "mode": "0755", "msg": "refusing to convert from directory to symlink for /home/zweilos/wordlists", "owner": "zweilos", "path": "/home/zweilos/wordlists", "size": 4096, "state": "directory", "uid": 1000}

Fix:  put in subfolder instead of trying to link to existing folder

```yaml
# Add symlinks
- name: Create symbolic link to wordlists folder
  file:
    src: "/usr/share/wordlists"
    dest: "/home/{{user}}/wordlists/wordlists"
    state: link
```
