### ISSUE TITLE
apt doesnt show progress while installing

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/kali-ansible-setup#6]
Does it work?  Is it still running or has it hung?  Who knows?

https://www.reddit.com/r/ansible/comments/cwscqj/viewing_the_output_of_aptget/

Proposed fix:

```yaml
    - hosts: all
      tasks:

      - shell: ls
        register: apt_result

      - name: Update all packages to the latest version
        become: true
        apt:
            upgrade: "yes"
            update_cache: yes
            cache_valid_time: 86400
            force_apt_get: "yes"
        register: apt_result

      - debug:
          var: apt_result.stderr

```
